### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by schuhschuh** [MIRTK/MALPEM#1]
Refactor Christian's [MALPEM package](https://github.com/ledigchr/MALPEM) to make it a MIRTK extension package which uses MIRTK commands instead of deprecated IRTK binaries. 

## MIRTK replacements

- `seg_maths` (NiftySeg): `mirtk.calculate_element_wise`
    - `-bin`: use (current image>0) to binarise
        - `seg_maths image.nii -bin mask.nii`
        - `mirtk.calculate_element_wise('image.nii', '-threshold-le', 0, '-pad', 0, '-set', 1, '-out', 'mask.nii')`
    - `-thr`
    - `-uthr`
    - `-mul`
    - `-add`
    - `-sub`
    - `-div`
- `cl_create4D`: `mirtk.combine_images`
- `cl_pairwiseSymDOF`: `mirtk.average_dofs`
- `cl_apply_mask`
    - `mirtk.calculate_element_wise('scan.nii', '-mask', 'mask.nii', '-pad', -1, '-out', brain.nii')`
- `convert`: `mirtk.convert_image`
- `cl_extract_frame`: `mirtk.extract_image_volume`
- `cl_averageDOFs`: `mirtk.average_dofs`
- `dofinvert`: `mirtk.invert_dof`
- `dofcombine`: `mirtk.compose_dofs`
- `ireg`: `mirtk.register`
- `transformation`: `mirtk.transform_image`
- `display`: Use `mirtk.rendering.screenshots` module for report generation.

## Custom tools

- `cl_compute_volume`: Consider adding this to core MIRTK applications
- `cl_gaussian_fusion`
- `cl_malpem`
- `cl_malpem4D`
- `pincram-0.2.3_ireg.sh` (see below)
- `scale.sh` (see below)

## External dependencies

- `N4` (also used by [Draw-EM](https://github.com/MIRTK/DrawEM) package, see [here](https://github.com/MIRTK/DrawEM/tree/master/ThirdParty/ITK)... though binary shouldn't be in repo)

**Comment by schuhschuh** [comment]
[PINCRAM script](https://github.com/ledigchr/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/pincram/pincram-0.2.3_ireg.sh):
- `ireg`: `mirtk register`
- `seg_maths` operations: `-div`, `-thr`, `-bin`: `mirtk calculate-element-wise` 
- `dofcombine`: `mirtk compose-dofs`
- `transformation`: `mirtk transform-image`
- `headertool`
   - `-origin <x> <y> <z>`
   - `mirtk edit-image a.nii.gz b.nii.gz -origin <x> <y> <z>`
- `convert` to `-float`: `mirtk convert-image in.nii out.nii -float`
- `dilation`: `mirtk dilate-image`
- `erosion`: `mirtk erode-image`
- `subtract`: `mirtk calculate-element-wise a.nii -sub b.nii -out a_minus_b.nii`
- `padding`
- `labelStats`
- `evaluation`: `evaluation emasked-$thislevel.nii.gz $srctr -Tp 0 -mask emargin-$thislevel-dil.nii.gz -linear | grep NMI | cut -d ' ' -f 2 `

**Comment by schuhschuh** [comment]
[scale.sh](https://github.com/ledigchr/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/scale):
- `seg_stats` (NiftySeg) options (see [here](http://nipype.readthedocs.io/en/latest/interfaces/generated/interfaces.niftyseg/stats.html)):
    - `-t 1`: Only estimate statistics if voxel is larger than 1
    - `-R`: The robust range (assuming 2% outliers on both sides) of all voxels
    - `mirtk calculate-element-wise img.nii -threshold 1 -pct 2 98 -d ' '`
- `seg_maths` (NiftySeg) operations: `-thr`, `-bin`, `-mul`, `-uthr`, `-add`

```
$maths_ms $input_ms -thr $max_ms -bin -mul 255 $peaks_ms

fac_ms=$(echo "scale=5; 255/$max_ms" | /usr/bin/bc)
echo $fac_ms

$maths_ms $input_ms -mul $fac_ms -uthr 255 -add $peaks_ms $output_ms
$maths_ms $output_ms -thr 257 -bin -mul 255 $peaks_ms
$maths_ms $output_ms -uthr 256 -add $peaks_ms $output_ms

$maths_ms $input_ms -uthr 0 -mul -1 -bin -mul -1 $tmp_ms
$maths_ms $output_ms -thr 0 -add $tmp_ms $output_ms
```

- `cl_erosion` (5 iterations):
   - Input is grey-scale image
   - Binarise by setting values >0 to one and zero otherwise
   - Erode this binary mask
   - Set all input grey-scale values outside of mask to zero, keep other values unchanged

**Comment by schuhschuh** [comment]
`myProbabilisticAtlas` adds `SwapImages` function, which is also in [Draw-EM's implementation](https://github.com/MIRTK/DrawEM/blob/aee8fba4274378e9cf4bd4a499ffa03946f863f1/include/mirtk/ProbabilisticAtlas.h#L67).

**Comment by schuhschuh** [comment]
## To-Do list
1. Remove [proot](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/bin/malpem-proot) script.
2. Refactor PINCRAM Bash script:
   - [ ] Move [common](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/pincram/common) functions directly inside [pincram](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/pincram/pincram-0.2.3_ireg.sh#L4) script.
    - [ ] Use `mirtk calculate-element-wise` instead of `seg_maths`.
    - [ ] Any replacement for [labelStats](https://bitbucket.org/ledigchr/irtk_malpem_source/src/902a57c28472afa07ba99da253863cfd220ee0f8/irtk/applications/labelStats.cc?at=master&fileviewer=file-view-default) available? How about [mirtk evaluate-overlap](https://github.com/BioMedIA/MIRTK/blob/cf264db38e49a6711c1b3562184e07c9a110eecf/Applications/src/evaluate-overlap.cc)?
        - Usage: `labelStats ref.nii.gz assess.nii.gz -q | cut -d ',' -f 1`
        - `-q`: Quiet summary, CSV output: `OR,Dice` (mean values over all labels)
        - Add `-mean` option or similar to `evaluate-overlap` command.
3. Refactor C++ implementation of required custom commands:
    - [ ] [cl_compute_volume](https://bitbucket.org/ledigchr/irtk_malpem_source/src/902a57c28472afa07ba99da253863cfd220ee0f8/irtk/myTools/applications/compute_volume.cc?at=master&fileviewer=file-view-default) --> `mirtk malpem-compute-volume`
    - [ ] [cl_gaussian_fusion](https://bitbucket.org/ledigchr/irtk_malpem_source/src/902a57c28472afa07ba99da253863cfd220ee0f8/irtk/myTools/applications/gaussian_fusion.cc?at=master&fileviewer=file-view-default) --> `mirtk malpem-gaussian-fusion`
    - [ ] [cl_malpem](https://bitbucket.org/ledigchr/irtk_malpem_source/src/902a57c28472afa07ba99da253863cfd220ee0f8/irtk/mySegmentation/applications/malpem.cc?at=master&fileviewer=file-view-default) --> `mirtk malpem-refinement`
    - [ ] [cl_malpem4D](https://bitbucket.org/ledigchr/irtk_malpem_source/src/902a57c28472afa07ba99da253863cfd220ee0f8/irtk/mySegmentation/applications/malpem4D.cc?at=master&fileviewer=file-view-default) --> `mirtk malpem-longitudinal-refinement`
4. Refactor MALPEM Python modules:
    - [x] Execute MIRTK commands using [mirtk.run](https://github.com/BioMedIA/MIRTK/blob/cf264db38e49a6711c1b3562184e07c9a110eecf/Applications/lib/python/mirtk/__init__.py.in#L85), more conveniently as:
        - `import mirtk`
        - `mirtk.run('<command>', args=[], opts={})` --> `mirtk.<command>(*args, **kwargs)`.
    - [ ] Rename [malpem.mytools](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/mytools.py) to `malpem.tools` and update all references.
    - [ ] [malpem.bias_correction](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/bias_correction.py)
    - [ ] [malpem.brain_extraction](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/brain_extraction.py)
    - [ ] [malpem.intensity_normalise](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/intensity_normalise.py)
      - Implement [scale](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/scale) functionality using MIRTK tools directly in [malpem.intensity_normalise.robust_rescale](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/intensity_normalise.py#L11) function.
    - [ ] [malpem.label_fusion](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/label_fusion.py)
    - [ ] [malpem.label_refinement](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/label_refinement.py)
    - [ ] [malpem.registration](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/registration.py)
    - [ ] [malpem.report](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/lib/malpem/report.py)
        - Use [mirtk.rendering.screenshots](https://github.com/MIRTK/Scripting/blob/1beb803240bb3bf8ec978fcc822d80b7432e6d76/lib/python/mirtk/rendering/screenshots.py) module.
5. Update [installer](https://github.com/MIRTK/MALPEM/blob/eb71e980bacbda2304b3386f5017272b20d71c9e/installer/malpem-install) script.
6. Update README and LICENSE.
7. Include package in main [MIRTK](https://github.com/BioMedIA/MIRTK) repository as [optional extension package](https://github.com/BioMedIA/MIRTK/blob/cf264db38e49a6711c1b3562184e07c9a110eecf/BasisProject.cmake#L73) (Git submodule).
